### ISSUE TITLE
Board and Enclosure mockup for Prototype #1

### ISSUE THREAD

**Issue by LokiMetaSmith** [PubInv/general-alarm-device#32]

**Comment by LokiMetaSmith** [comment]
Move the uno by rotating it 90 degrees such that the connectors come from the bottom.

Move the interfering LEDs vertically such that they are to the side of the LCD display.

Move the reset button and LCD contrast potentiometer to the side of the board with the LCD

**Comment by ForrestErickson** [comment]
20220724 0724 push changes to main.
Note I am not sure of the centering on adjustment screw on the silk screen of the contrast control pot.  
Should the POWER LED move up and perhaps the contrast control pot move down?
PCB screen shot:
![image](https://user-images.githubusercontent.com/5836181/180644689-20faadc6-151b-40d4-b3d4-c604b99abad4.png)

3D render Front aka component side:
![image](https://user-images.githubusercontent.com/5836181/180644709-d8cf3c4e-8f1e-4ed4-a006-c5882ce3416a.png)


3D render Back aka Display side:
![image](https://user-images.githubusercontent.com/5836181/180644751-14e99c7d-d6f0-47b9-99cc-f0531d339a42.png)

**Comment by ForrestErickson** [comment]
Oops, J105 is not on grid. Will need to fix once the schematic loads again.
![image](https://user-images.githubusercontent.com/5836181/180647770-bb54dbe7-e071-4636-b372-4677fc5d4578.png)

**Comment by ForrestErickson** [comment]
Fixed the library and schematic error and tweeked the location of J105.

At 16:09 EDT I have pushed the change to github.
Ready for review.

**Comment by ForrestErickson** [comment]
The centering on the contrast POT is hard to understand.
The relation between axis where the tool turns the pot and pins and the component outline is more than I can understand this late in my day.

Here is a drawing for the 3/8" part: https://www.bourns.com/docs/Product-Datasheets/3386.pdf

**Comment by ForrestErickson** [comment]
20220725 Morning of, I found a 3D model for Arduino UNO on grabcad and made a footprint for it and pulled it in. Good thing too because it made me realized **I have to flip the UNO footprint** from PCB top to bottom to be correct.

Will need to allow for about 0.350 of female connector height and 0.100 of pin header height.
These settings get the PCB flush.
![image](https://user-images.githubusercontent.com/5836181/180789669-0abe22e1-ffdb-45f8-8711-3c7c64222058.png)

For an offset of -.575 which looks like this.
![image](https://user-images.githubusercontent.com/5836181/180789845-0251784d-48e7-409d-a3fa-22cc7d632435.png)

Here it is after putting the footprint on back.
![image](https://user-images.githubusercontent.com/5836181/180791585-1704656f-e6a7-4000-92f0-f93419229184.png)
and
![image](https://user-images.githubusercontent.com/5836181/180792165-e4623eff-2143-4036-9807-4a2eff96f010.png)


I rotated the uController and near buy circuits too.
![image](https://user-images.githubusercontent.com/5836181/180791737-45af4024-f9d6-4130-a8e0-56ccb725c412.png)

**Comment by ForrestErickson** [comment]
New push as of 20220725 10:11 EDT.

**Comment by ForrestErickson** [comment]
Possible Spacer for LCD from PCB
https://www.mcmaster.com/94639A702/
Shape	Round
Material	Nylon 6/6 Plastic
OD	3/16"
OD Tolerance	-0.015" to 0.015"
Length	1/8"
Length Tolerance	-0.015" to 0.015"
For Screw Size	No. 4

We will need a screw long enough to go through 2x 0.0625 + 0.125 + thread engagement of 0.125 = 0.375
This part looks good:
https://www.mcmaster.com/90272A108/
Zinc-Plated Steel Pan Head Phillips Screw
4-40 Thread, 3/8" Long
Threading	Fully Threaded
Head Diameter	0.219"
Head Height	0.080"
Drive Style	Phillips

We will need nuts.
Steel Locknuts with External-Tooth Lock Washer
https://www.mcmaster.com/90675A005/
Material	Zinc-Plated Steel
Thread Size
4-40
Thread Type	UNC
Thread Spacing 
Thread Fit	Class 2B
Thread Direction	Right Hand
Width	1/4"
Height	7/64"

Shopping cart totals less than $18 exclusive of shipping.
![image](https://user-images.githubusercontent.com/5836181/180844038-4e484ca1-70a8-4eef-9309-a9544edcd428.png)

**Comment by ForrestErickson** [comment]
All parts affecting enclosure on PCB locked with commit pushed at 20220725 about 16:55 EDT.

**Comment by LokiMetaSmith** [comment]
Closing this as the V1 boards have been built up.
